### ISSUE TITLE
Make Background Static to Avoid issues while scrolling

### ISSUE THREAD

**Issue by firepig** [firepig/The_Timekeeper#3]
### Issue Title: Make Background Static to Avoid Repeating
**Description:**
The current background image of the application repeats as the user scrolls through the page. This results in an unprofessional look and can be distracting for users. The background should remain fixed while the foreground content moves. 

**Steps to Reproduce:**

Navigate to any page of the application.
Scroll down the page.
Observe the repeating background. 
Expected Result:
The background image should remain static and not repeat as the user scrolls.

**Actual Result:**
The background image repeats as the user scrolls through the page.

Screenshots:
![image](https://github.com/firepig/The_Timekeeper/assets/906587/1cd3319b-11ac-470a-9d83-5df5dbbceef8)

Priority:
medium

**Comment by Anuj-892** [comment]
Could i work on this issue? First time contributor here.

**Comment by firepig** [comment]
Fixed issue and added some UI enhancements.
